version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: terraform
  directory: "/tests/test_delete_default_vpc"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
